package ru.geekbrains.db.model;

import lombok.AllArgsConstructor;
import lombok.ToString;

@ToString
@AllArgsConstructor

public class Categories {


    public Categories(String title) {
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Sep 11 15:24:15 MSK 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.title
     *
     * @mbg.generated Sat Sep 11 15:24:15 MSK 2021
     */
    private String title;

    public Categories(int i) {

    }

    public Categories() {

    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.id
     *
     * @return the value of categories.id
     *
     * @mbg.generated Sat Sep 11 15:24:15 MSK 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.id
     *
     * @param id the value for categories.id
     *
     * @mbg.generated Sat Sep 11 15:24:15 MSK 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.title
     *
     * @return the value of categories.title
     *
     * @mbg.generated Sat Sep 11 15:24:15 MSK 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.title
     *
     * @param title the value for categories.title
     *
     * @mbg.generated Sat Sep 11 15:24:15 MSK 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}